In [15]:
# import liabrary
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/file.csv")

In [ ]:
df.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 426 entries, 0 to 431
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         426 non-null    object
 1   Model        426 non-null    object
 2   Type         426 non-null    object
 3   Origin       426 non-null    object
 4   DriveTrain   426 non-null    object
 5   MSRP         426 non-null    object
 6   Invoice      426 non-null    object
 7   EngineSize   426 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   426 non-null    float64
 10  MPG_City     426 non-null    float64
 11  MPG_Highway  426 non-null    float64
 12  Weight       426 non-null    float64
 13  Wheelbase    426 non-null    float64
 14  Length       426 non-null    float64
dtypes: float64(8), object(7)
memory usage: 53.2+ KB

In [25]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [28]:
df.Cylinders.fillna(df['Cylinders'].mean())

0      6.0
1      4.0
2      4.0
3      6.0
4      6.0
      ...
427    5.0
428    5.0
429    6.0
430    4.0
431    5.0
Name: Cylinders, Length: 426, dtype: float64

In [17]:
df['Cylinders'].unique()

array([ 6.,  4.,  8., 10.,  3., 12.,  5.])

In [18]:
df['EngineSize'].unique()

array([3.5, 2. , 2.4, 3.2, 1.8, 3. , 2.7, 4.2, 4.4, 2.5, 3.4, 3.1, 3.8,
       5.3, 4.6, 3.6, 6. , 1.6, 2.2, 4.3, 5.7, 2.8, 3.3, 4.7, 8.3, 3.7,
       6.8, 4. , 3.9, 5.4, 2.3, 4.8, 1.4, 1.7, 4.5, 5. , 2.6, 5.5, 5.6,
       1.5, 1.9, 2.9])

In [38]:
df["Origin"].value_counts()

Origin
Asia      156
USA       147
Europe    123
Name: count, dtype: int64

In [30]:
df['Make'].info()

<class 'pandas.core.series.Series'>
Index: 426 entries, 0 to 431
Series name: Make
Non-Null Count  Dtype
--------------  -----
426 non-null    object
dtypes: object(1)
memory usage: 6.7+ KB

In [31]:
df['Make'].value_counts()

Make
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Hyundai          12
Jaguar           12
Volvo            12
Subaru           11
Pontiac          11
Lexus            11
Kia              11
Lincoln           9
Buick             9
Mazda             9
Mercury           9
Saturn            8
Cadillac          8
Suzuki            8
Infiniti          8
GMC               8
Acura             7
Porsche           7
Saab              7
Land Rover        3
Oldsmobile        3
Jeep              3
Scion             2
Isuzu             2
MINI              2
Hummer            1
Name: count, dtype: int64

In [42]:
df = df.dropna(subset=["Weight"], how="any",inplace=True)
df = df[df["Weight"] > 4000]

TypeError: 'NoneType' object is not subscriptable

In [41]:
df["Weight"].value_counts()

Weight
4024.0    3
4052.0    3
4057.0    3
4309.0    2
4369.0    2
         ..
4463.0    1
5000.0    1
7190.0    1
4542.0    1
4638.0    1
Name: count, Length: 93, dtype: int64